# this is a sample robot configuration file that would be called `sample_config' based on the filename.
# this is a yaml file with the following format: 

# dead_end_links: ["dead_end_link_1"] 
# inactive_joints: ["inactive_joint_1", "inactive_joint_2"] 
# mobile_base_mode: "static" 
#    ^^(can be static, floating, translation, rotation, planar_translation, planar_rotation, planar_translation_and_rotation)

dead_end_links: [] 
inactive_joints: [] 
mobile_base_mode: "static" 
