# this is a sample robot configuration file that would be called `sample_config' based on the filename.
# this is a yaml file with the following format: 

# dead_end_links: ["dead_end_link_1"] 
# inactive_joints: ["inactive_joint_1", "inactive_joint_2"] 
# mobile_base_mode: "static" 
#    ^^(can be static, floating, translation, rotation, planar_translation, planar_rotation, planar_translation_and_rotation)
# mobile_base_bounds_filename: "None" 
#    ^^(can be None if no bounds should be placed on mobile base, or a name of a file in the mobile_base_bounds directory)
# base_position_offset: [0., 0., 0.] 
#    ^^(represented in meters)
# base_orientation_offset: [0., 0., 0.] 
#    ^^(Euler angles, represented in radians)

dead_end_links: [] 
inactive_joints: [] 
mobile_base_mode: "static" 
mobile_base_bounds_filename:
base_position_offset: [0., 0., 0.]
base_orientation_offset: [0., 0., 0.]
